site_name: RWBAtools
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/RWBA/rwbatools
pages:
- Welcome: index.md
- Fillings:
    - Widgets: Widgets.md
    - Images: Images.md
    - Sounds: Sound.md
    - Bars: Bars.md
    - Pop-ups: Dialogs.md
    - More to come...: DevWidgets.md
- Presentation:
    - Arranging widgets: Layout.md
    - Grouping widgets: Grouping2.md
    - Changing widgets: WidgetOptions.md
    - Extras: GuiOptions.md
- Lessons:
    - Lesson 1: empty.md
- About:
    - Installation: Install.md
    - Release notes: ReleaseNotes.md
    - License: License.md
    - Acknowledgements: Thanks.md
theme: united
copyright: <p>Richard Jarvis, 2016</p>
