site_name: RWBAtools
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/RWBA/rwbatools
pages:
- Home: index.md
- Creating a GUI:
    - Widgets: Widgets.md
    - Images: Images.md
    - Sounds: Sound.md
    - Bars: Bars.md
    - Dialogs: Dialogs.md
    - Under Development: DevWidgets.md
- Configuring a GUI:
    - Positioning Widgets: Layout.md
    - Grouping Widgets: Grouping.md
    - GUI Options: GuiOptions.md
    - Widget Options: WidgetOptions.md
- About:
    - License: License.md
    - Installation: Install.md
    - Release Notes: ReleaseNotes.md
    - Acknowledgements: Thanks.md
theme: united
copyright: <p>Richard Jarvis, 2016</p>
