site_name: RWBAtools
repo_url: https://github.com/RWBA/rwbatools
pages:
- Home: index.md
- Creating a GUI:
    - Layout: Layout.md
    - Widgets: Widgets.md
    - Widget Options: WidgetOptions.md
    - Bars: Bars.md
    - Dialogs: Dialogs.md
    - Sound: Sound.md
    - GUI Options: GuiOptions.md
    - Grouping Widgets: Grouping.md
    - Under Development: DevWidgets.md
- Recipes:
    - Empty: Empty.md
- About:
    - License: License.md
    - Release Notes: ReleaseNotes.md
    - Thanks: Thanks.md
theme: united
copyright: <p>Richard Jarvis, 2016</p>
