doc-warnings: false
test-warnings: false
strictness: veryhigh
max-line-length: 120
uses:
        - django
        - celery
        - flask
autodetect: true
requirements:
        - deps/core.txt
        - deps/test.txt
ignore-paths:
        - docs
        - dist
        - Lessons
        - releases
python-targets:
        - 3
