language: python

matrix:
    include:
        - os: linux
        sudo: required
        python: 2.7
        env: PYTHONPATH=.
        - os: linux
        sudo: required
        python: 3.2
        env: PYTHONPATH=.
        - os: linux
        sudo: required
        python: 3.3
        env: PYTHONPATH=.
        - os: linux
        sudo: required
        python: 3.4
        env: PYTHONPATH=.
        - os: linux
        sudo: required
        python: 3.5
        env: PYTHONPATH=.
        - os: osx
        language: generic
        env: PYTHONPATH=.
before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then virtualenv venv -p python3; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then source venv/bin/activate; fi
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install codeclimate-test-reporter

before_script:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 # give xvfb some time to start
    - VERS=`python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))'`

script:
    - coverage run --source=appJar tests/widget_test.py

after_success:
    - bash tests/run_coveralls.sh

addons:
    code_climate:
        repo_token: 3b1c31ab1ba5ee5eb7aaf75efd1245ee00e38a070f7a82fece4b5f7b9ca5f7f7
