site_name: appJar
site_url: http://appjar.info
site_favicon: img/favicon3.ico
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/RWBA/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
theme: united
theme_dir: custom_united
copyright: <p>Richard Jarvis, 2016</p>
site_description: Python library for building simple tkinter guis
site_author: Richard Jarvis
extra_css: [extra.css]
pages:
- Welcome: index.md
- Fillings:
    - Widgets: Widgets.md
    - Images: Images.md
    - Sounds: Sound.md
    - Bars: Bars.md
    - Pop-ups: Dialogs.md
    - In the works...: DevWidgets.md
- Presentation:
    - Arranging widgets: Layout.md
    - Grouping widgets: Grouping.md
    - Changing widgets: WidgetOptions.md
    - Extras: GuiOptions.md
- About:
    - Installation: Install.md
    - Acknowledgements: Thanks.md
    - Python: PythonBasics.md
    - License: License.md
