site_name: appJar
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/RWBA/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
theme: yeti
copyright: <p>Richard Jarvis, 2016</p>
pages:
- Welcome: index.md
- Fillings:
    - Widgets: Widgets.md
    - Images: Images.md
    - Sounds: Sound.md
    - Bars: Bars.md
    - Pop-ups: Dialogs.md
    - Still to come...: DevWidgets.md
- Presentation:
    - Arranging widgets: Layout.md
    - Grouping widgets: Grouping.md
    - Changing widgets: WidgetOptions.md
    - Extras: GuiOptions.md
- Lessons:
    - Basic Python: Empty.md
    - Advanced Python: Empty.md
    - Turtle Programming: Empty.md
    - GUI Programming: Empty.md
    - Files & Databases: Empty.md
    - Object-Oriented Programming: Empty.md
- Python: PythonBasics.md
- About:
    - Installation: Install.md
    - Acknowledgements: Thanks.md
    - License: License.md
