site_name: appJar
site_url: http://appjar.info
site_favicon: img/favicon3.ico
site_dir: ../../../jarvisteach.github.io/
repo_url: https://github.com/RWBA/appJar
google_analytics: ['UA-79206647-1', 'appjar.info']
theme: united
theme_dir: custom_united
copyright: <p>Richard Jarvis, 2016</p>
site_description: Python library for building simple tkinter guis
site_author: Richard Jarvis
extra_css: [extra.css]
strict: true
pages:
- Welcome: index.md
- Fillings:
    - Widgets: pythonWidgets.md
    - Images: pythonImages.md
    - Sounds: pythonSound.md
    - Bars: pythonBars.md
    - Pop-ups: pythonDialogs.md
    - In the works...: pythonDevWidgets.md
- Presentation:
    - Arranging widgets: pythonWidgetLayout.md
    - Grouping widgets: pythonWidgetGrouping.md
    - Changing widgets: pythonWidgetOptions.md
    - GUI Options: pythonGuiOptions.md
    - GUI Events: pythonEvents.md
- About:
    - Set-up: Install.md
    - Acknowledgements: Thanks.md
    - Python: pythonBasics.md
    - License: License.md
